### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by 354651432** [linuxthor/inode-ctime#1]
`make -C /lib/modules/3.10.0-862.14.4.el7.x86_64/build SUBDIRS=/home/super/inode-ctime modules
make: *** /lib/modules/3.10.0-862.14.4.el7.x86_64/build: No such file or directory.  Stop.
make: *** [default] Error 2`

but the directory is exists
`lrwxrwxrwx 1 root root 43 Nov 16  2018 /lib/modules/3.10.0-862.14.4.el7.x86_64/build -> /usr/src/kernels/3.10.0-862.14.4.el7.x86_64`

env: `LSB Version:    :core-4.1-amd64:core-4.1-noarch Linux 3.10.0-862.14.4.el7.x86_64`

**Comment by linuxthor** [comment]
It builds OK for me (I hadn't tried in a few years!) Are other modules building OK, just not this one? 

It seems almost like your kernel headers are missing or damaged somehow.
